/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConfigsRouteImport } from './routes/configs'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemTrayIndexRouteImport } from './routes/system-tray/index'
import { Route as SearchViewIndexRouteImport } from './routes/search-view/index'
import { Route as NotebookIndexRouteImport } from './routes/notebook/index'
import { Route as NotebookAddIndexRouteImport } from './routes/notebook-add/index'
import { Route as ExternalUseIndexRouteImport } from './routes/external-use/index'
import { Route as ConfigsWindowCommunicationRouteImport } from './routes/configs/window-communication'
import { Route as ConfigsFormTestRouteImport } from './routes/configs/form-test'
import { Route as ConfigsAppInfoRouteImport } from './routes/configs/app-info'
import { Route as ConfigsPronunciationIndexRouteImport } from './routes/configs/pronunciation/index'
import { Route as ConfigsNotebookIndexRouteImport } from './routes/configs/notebook/index'
import { Route as ConfigsImportExportIndexRouteImport } from './routes/configs/import-export/index'
import { Route as ConfigsGeneralIndexRouteImport } from './routes/configs/general/index'
import { Route as ConfigsDictionariesIndexRouteImport } from './routes/configs/dictionaries/index'
import { Route as ConfigsDictPanelIndexRouteImport } from './routes/configs/dict-panel/index'
import { Route as ConfigsDictAuthIndexRouteImport } from './routes/configs/dict-auth/index'
import { Route as ConfigsContextMenusIndexRouteImport } from './routes/configs/context-menus/index'

const ConfigsRoute = ConfigsRouteImport.update({
  id: '/configs',
  path: '/configs',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemTrayIndexRoute = SystemTrayIndexRouteImport.update({
  id: '/system-tray/',
  path: '/system-tray/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchViewIndexRoute = SearchViewIndexRouteImport.update({
  id: '/search-view/',
  path: '/search-view/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookIndexRoute = NotebookIndexRouteImport.update({
  id: '/notebook/',
  path: '/notebook/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookAddIndexRoute = NotebookAddIndexRouteImport.update({
  id: '/notebook-add/',
  path: '/notebook-add/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternalUseIndexRoute = ExternalUseIndexRouteImport.update({
  id: '/external-use/',
  path: '/external-use/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigsWindowCommunicationRoute =
  ConfigsWindowCommunicationRouteImport.update({
    id: '/window-communication',
    path: '/window-communication',
    getParentRoute: () => ConfigsRoute,
  } as any)
const ConfigsFormTestRoute = ConfigsFormTestRouteImport.update({
  id: '/form-test',
  path: '/form-test',
  getParentRoute: () => ConfigsRoute,
} as any)
const ConfigsAppInfoRoute = ConfigsAppInfoRouteImport.update({
  id: '/app-info',
  path: '/app-info',
  getParentRoute: () => ConfigsRoute,
} as any)
const ConfigsPronunciationIndexRoute =
  ConfigsPronunciationIndexRouteImport.update({
    id: '/pronunciation/',
    path: '/pronunciation/',
    getParentRoute: () => ConfigsRoute,
  } as any)
const ConfigsNotebookIndexRoute = ConfigsNotebookIndexRouteImport.update({
  id: '/notebook/',
  path: '/notebook/',
  getParentRoute: () => ConfigsRoute,
} as any)
const ConfigsImportExportIndexRoute =
  ConfigsImportExportIndexRouteImport.update({
    id: '/import-export/',
    path: '/import-export/',
    getParentRoute: () => ConfigsRoute,
  } as any)
const ConfigsGeneralIndexRoute = ConfigsGeneralIndexRouteImport.update({
  id: '/general/',
  path: '/general/',
  getParentRoute: () => ConfigsRoute,
} as any)
const ConfigsDictionariesIndexRoute =
  ConfigsDictionariesIndexRouteImport.update({
    id: '/dictionaries/',
    path: '/dictionaries/',
    getParentRoute: () => ConfigsRoute,
  } as any)
const ConfigsDictPanelIndexRoute = ConfigsDictPanelIndexRouteImport.update({
  id: '/dict-panel/',
  path: '/dict-panel/',
  getParentRoute: () => ConfigsRoute,
} as any)
const ConfigsDictAuthIndexRoute = ConfigsDictAuthIndexRouteImport.update({
  id: '/dict-auth/',
  path: '/dict-auth/',
  getParentRoute: () => ConfigsRoute,
} as any)
const ConfigsContextMenusIndexRoute =
  ConfigsContextMenusIndexRouteImport.update({
    id: '/context-menus/',
    path: '/context-menus/',
    getParentRoute: () => ConfigsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/configs': typeof ConfigsRouteWithChildren
  '/configs/app-info': typeof ConfigsAppInfoRoute
  '/configs/form-test': typeof ConfigsFormTestRoute
  '/configs/window-communication': typeof ConfigsWindowCommunicationRoute
  '/external-use/': typeof ExternalUseIndexRoute
  '/notebook-add/': typeof NotebookAddIndexRoute
  '/notebook/': typeof NotebookIndexRoute
  '/search-view/': typeof SearchViewIndexRoute
  '/system-tray/': typeof SystemTrayIndexRoute
  '/configs/context-menus/': typeof ConfigsContextMenusIndexRoute
  '/configs/dict-auth/': typeof ConfigsDictAuthIndexRoute
  '/configs/dict-panel/': typeof ConfigsDictPanelIndexRoute
  '/configs/dictionaries/': typeof ConfigsDictionariesIndexRoute
  '/configs/general/': typeof ConfigsGeneralIndexRoute
  '/configs/import-export/': typeof ConfigsImportExportIndexRoute
  '/configs/notebook/': typeof ConfigsNotebookIndexRoute
  '/configs/pronunciation/': typeof ConfigsPronunciationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/configs': typeof ConfigsRouteWithChildren
  '/configs/app-info': typeof ConfigsAppInfoRoute
  '/configs/form-test': typeof ConfigsFormTestRoute
  '/configs/window-communication': typeof ConfigsWindowCommunicationRoute
  '/external-use': typeof ExternalUseIndexRoute
  '/notebook-add': typeof NotebookAddIndexRoute
  '/notebook': typeof NotebookIndexRoute
  '/search-view': typeof SearchViewIndexRoute
  '/system-tray': typeof SystemTrayIndexRoute
  '/configs/context-menus': typeof ConfigsContextMenusIndexRoute
  '/configs/dict-auth': typeof ConfigsDictAuthIndexRoute
  '/configs/dict-panel': typeof ConfigsDictPanelIndexRoute
  '/configs/dictionaries': typeof ConfigsDictionariesIndexRoute
  '/configs/general': typeof ConfigsGeneralIndexRoute
  '/configs/import-export': typeof ConfigsImportExportIndexRoute
  '/configs/notebook': typeof ConfigsNotebookIndexRoute
  '/configs/pronunciation': typeof ConfigsPronunciationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/configs': typeof ConfigsRouteWithChildren
  '/configs/app-info': typeof ConfigsAppInfoRoute
  '/configs/form-test': typeof ConfigsFormTestRoute
  '/configs/window-communication': typeof ConfigsWindowCommunicationRoute
  '/external-use/': typeof ExternalUseIndexRoute
  '/notebook-add/': typeof NotebookAddIndexRoute
  '/notebook/': typeof NotebookIndexRoute
  '/search-view/': typeof SearchViewIndexRoute
  '/system-tray/': typeof SystemTrayIndexRoute
  '/configs/context-menus/': typeof ConfigsContextMenusIndexRoute
  '/configs/dict-auth/': typeof ConfigsDictAuthIndexRoute
  '/configs/dict-panel/': typeof ConfigsDictPanelIndexRoute
  '/configs/dictionaries/': typeof ConfigsDictionariesIndexRoute
  '/configs/general/': typeof ConfigsGeneralIndexRoute
  '/configs/import-export/': typeof ConfigsImportExportIndexRoute
  '/configs/notebook/': typeof ConfigsNotebookIndexRoute
  '/configs/pronunciation/': typeof ConfigsPronunciationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/configs'
    | '/configs/app-info'
    | '/configs/form-test'
    | '/configs/window-communication'
    | '/external-use/'
    | '/notebook-add/'
    | '/notebook/'
    | '/search-view/'
    | '/system-tray/'
    | '/configs/context-menus/'
    | '/configs/dict-auth/'
    | '/configs/dict-panel/'
    | '/configs/dictionaries/'
    | '/configs/general/'
    | '/configs/import-export/'
    | '/configs/notebook/'
    | '/configs/pronunciation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/configs'
    | '/configs/app-info'
    | '/configs/form-test'
    | '/configs/window-communication'
    | '/external-use'
    | '/notebook-add'
    | '/notebook'
    | '/search-view'
    | '/system-tray'
    | '/configs/context-menus'
    | '/configs/dict-auth'
    | '/configs/dict-panel'
    | '/configs/dictionaries'
    | '/configs/general'
    | '/configs/import-export'
    | '/configs/notebook'
    | '/configs/pronunciation'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/configs'
    | '/configs/app-info'
    | '/configs/form-test'
    | '/configs/window-communication'
    | '/external-use/'
    | '/notebook-add/'
    | '/notebook/'
    | '/search-view/'
    | '/system-tray/'
    | '/configs/context-menus/'
    | '/configs/dict-auth/'
    | '/configs/dict-panel/'
    | '/configs/dictionaries/'
    | '/configs/general/'
    | '/configs/import-export/'
    | '/configs/notebook/'
    | '/configs/pronunciation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  ConfigsRoute: typeof ConfigsRouteWithChildren
  ExternalUseIndexRoute: typeof ExternalUseIndexRoute
  NotebookAddIndexRoute: typeof NotebookAddIndexRoute
  NotebookIndexRoute: typeof NotebookIndexRoute
  SearchViewIndexRoute: typeof SearchViewIndexRoute
  SystemTrayIndexRoute: typeof SystemTrayIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/configs': {
      id: '/configs'
      path: '/configs'
      fullPath: '/configs'
      preLoaderRoute: typeof ConfigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-tray/': {
      id: '/system-tray/'
      path: '/system-tray'
      fullPath: '/system-tray/'
      preLoaderRoute: typeof SystemTrayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-view/': {
      id: '/search-view/'
      path: '/search-view'
      fullPath: '/search-view/'
      preLoaderRoute: typeof SearchViewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook/': {
      id: '/notebook/'
      path: '/notebook'
      fullPath: '/notebook/'
      preLoaderRoute: typeof NotebookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook-add/': {
      id: '/notebook-add/'
      path: '/notebook-add'
      fullPath: '/notebook-add/'
      preLoaderRoute: typeof NotebookAddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/external-use/': {
      id: '/external-use/'
      path: '/external-use'
      fullPath: '/external-use/'
      preLoaderRoute: typeof ExternalUseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configs/window-communication': {
      id: '/configs/window-communication'
      path: '/window-communication'
      fullPath: '/configs/window-communication'
      preLoaderRoute: typeof ConfigsWindowCommunicationRouteImport
      parentRoute: typeof ConfigsRoute
    }
    '/configs/form-test': {
      id: '/configs/form-test'
      path: '/form-test'
      fullPath: '/configs/form-test'
      preLoaderRoute: typeof ConfigsFormTestRouteImport
      parentRoute: typeof ConfigsRoute
    }
    '/configs/app-info': {
      id: '/configs/app-info'
      path: '/app-info'
      fullPath: '/configs/app-info'
      preLoaderRoute: typeof ConfigsAppInfoRouteImport
      parentRoute: typeof ConfigsRoute
    }
    '/configs/pronunciation/': {
      id: '/configs/pronunciation/'
      path: '/pronunciation'
      fullPath: '/configs/pronunciation/'
      preLoaderRoute: typeof ConfigsPronunciationIndexRouteImport
      parentRoute: typeof ConfigsRoute
    }
    '/configs/notebook/': {
      id: '/configs/notebook/'
      path: '/notebook'
      fullPath: '/configs/notebook/'
      preLoaderRoute: typeof ConfigsNotebookIndexRouteImport
      parentRoute: typeof ConfigsRoute
    }
    '/configs/import-export/': {
      id: '/configs/import-export/'
      path: '/import-export'
      fullPath: '/configs/import-export/'
      preLoaderRoute: typeof ConfigsImportExportIndexRouteImport
      parentRoute: typeof ConfigsRoute
    }
    '/configs/general/': {
      id: '/configs/general/'
      path: '/general'
      fullPath: '/configs/general/'
      preLoaderRoute: typeof ConfigsGeneralIndexRouteImport
      parentRoute: typeof ConfigsRoute
    }
    '/configs/dictionaries/': {
      id: '/configs/dictionaries/'
      path: '/dictionaries'
      fullPath: '/configs/dictionaries/'
      preLoaderRoute: typeof ConfigsDictionariesIndexRouteImport
      parentRoute: typeof ConfigsRoute
    }
    '/configs/dict-panel/': {
      id: '/configs/dict-panel/'
      path: '/dict-panel'
      fullPath: '/configs/dict-panel/'
      preLoaderRoute: typeof ConfigsDictPanelIndexRouteImport
      parentRoute: typeof ConfigsRoute
    }
    '/configs/dict-auth/': {
      id: '/configs/dict-auth/'
      path: '/dict-auth'
      fullPath: '/configs/dict-auth/'
      preLoaderRoute: typeof ConfigsDictAuthIndexRouteImport
      parentRoute: typeof ConfigsRoute
    }
    '/configs/context-menus/': {
      id: '/configs/context-menus/'
      path: '/context-menus'
      fullPath: '/configs/context-menus/'
      preLoaderRoute: typeof ConfigsContextMenusIndexRouteImport
      parentRoute: typeof ConfigsRoute
    }
  }
}

interface ConfigsRouteChildren {
  ConfigsAppInfoRoute: typeof ConfigsAppInfoRoute
  ConfigsFormTestRoute: typeof ConfigsFormTestRoute
  ConfigsWindowCommunicationRoute: typeof ConfigsWindowCommunicationRoute
  ConfigsContextMenusIndexRoute: typeof ConfigsContextMenusIndexRoute
  ConfigsDictAuthIndexRoute: typeof ConfigsDictAuthIndexRoute
  ConfigsDictPanelIndexRoute: typeof ConfigsDictPanelIndexRoute
  ConfigsDictionariesIndexRoute: typeof ConfigsDictionariesIndexRoute
  ConfigsGeneralIndexRoute: typeof ConfigsGeneralIndexRoute
  ConfigsImportExportIndexRoute: typeof ConfigsImportExportIndexRoute
  ConfigsNotebookIndexRoute: typeof ConfigsNotebookIndexRoute
  ConfigsPronunciationIndexRoute: typeof ConfigsPronunciationIndexRoute
}

const ConfigsRouteChildren: ConfigsRouteChildren = {
  ConfigsAppInfoRoute: ConfigsAppInfoRoute,
  ConfigsFormTestRoute: ConfigsFormTestRoute,
  ConfigsWindowCommunicationRoute: ConfigsWindowCommunicationRoute,
  ConfigsContextMenusIndexRoute: ConfigsContextMenusIndexRoute,
  ConfigsDictAuthIndexRoute: ConfigsDictAuthIndexRoute,
  ConfigsDictPanelIndexRoute: ConfigsDictPanelIndexRoute,
  ConfigsDictionariesIndexRoute: ConfigsDictionariesIndexRoute,
  ConfigsGeneralIndexRoute: ConfigsGeneralIndexRoute,
  ConfigsImportExportIndexRoute: ConfigsImportExportIndexRoute,
  ConfigsNotebookIndexRoute: ConfigsNotebookIndexRoute,
  ConfigsPronunciationIndexRoute: ConfigsPronunciationIndexRoute,
}

const ConfigsRouteWithChildren =
  ConfigsRoute._addFileChildren(ConfigsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  ConfigsRoute: ConfigsRouteWithChildren,
  ExternalUseIndexRoute: ExternalUseIndexRoute,
  NotebookAddIndexRoute: NotebookAddIndexRoute,
  NotebookIndexRoute: NotebookIndexRoute,
  SearchViewIndexRoute: SearchViewIndexRoute,
  SystemTrayIndexRoute: SystemTrayIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
