/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemTrayIndexRouteImport } from './routes/system-tray/index'
import { Route as SearchViewIndexRouteImport } from './routes/search-view/index'
import { Route as NotebookIndexRouteImport } from './routes/notebook/index'
import { Route as NotebookAddIndexRouteImport } from './routes/notebook-add/index'
import { Route as FormExampleIndexRouteImport } from './routes/form-example/index'
import { Route as ConfigsIndexRouteImport } from './routes/configs/index'
import { Route as ConfigsNotebookIndexRouteImport } from './routes/configs/notebook/index'

const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemTrayIndexRoute = SystemTrayIndexRouteImport.update({
  id: '/system-tray/',
  path: '/system-tray/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchViewIndexRoute = SearchViewIndexRouteImport.update({
  id: '/search-view/',
  path: '/search-view/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookIndexRoute = NotebookIndexRouteImport.update({
  id: '/notebook/',
  path: '/notebook/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookAddIndexRoute = NotebookAddIndexRouteImport.update({
  id: '/notebook-add/',
  path: '/notebook-add/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormExampleIndexRoute = FormExampleIndexRouteImport.update({
  id: '/form-example/',
  path: '/form-example/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigsIndexRoute = ConfigsIndexRouteImport.update({
  id: '/configs/',
  path: '/configs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigsNotebookIndexRoute = ConfigsNotebookIndexRouteImport.update({
  id: '/configs/notebook/',
  path: '/configs/notebook/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/configs/': typeof ConfigsIndexRoute
  '/form-example/': typeof FormExampleIndexRoute
  '/notebook-add/': typeof NotebookAddIndexRoute
  '/notebook/': typeof NotebookIndexRoute
  '/search-view/': typeof SearchViewIndexRoute
  '/system-tray/': typeof SystemTrayIndexRoute
  '/configs/notebook/': typeof ConfigsNotebookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/configs': typeof ConfigsIndexRoute
  '/form-example': typeof FormExampleIndexRoute
  '/notebook-add': typeof NotebookAddIndexRoute
  '/notebook': typeof NotebookIndexRoute
  '/search-view': typeof SearchViewIndexRoute
  '/system-tray': typeof SystemTrayIndexRoute
  '/configs/notebook': typeof ConfigsNotebookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/configs/': typeof ConfigsIndexRoute
  '/form-example/': typeof FormExampleIndexRoute
  '/notebook-add/': typeof NotebookAddIndexRoute
  '/notebook/': typeof NotebookIndexRoute
  '/search-view/': typeof SearchViewIndexRoute
  '/system-tray/': typeof SystemTrayIndexRoute
  '/configs/notebook/': typeof ConfigsNotebookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/configs/'
    | '/form-example/'
    | '/notebook-add/'
    | '/notebook/'
    | '/search-view/'
    | '/system-tray/'
    | '/configs/notebook/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/configs'
    | '/form-example'
    | '/notebook-add'
    | '/notebook'
    | '/search-view'
    | '/system-tray'
    | '/configs/notebook'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/configs/'
    | '/form-example/'
    | '/notebook-add/'
    | '/notebook/'
    | '/search-view/'
    | '/system-tray/'
    | '/configs/notebook/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  ConfigsIndexRoute: typeof ConfigsIndexRoute
  FormExampleIndexRoute: typeof FormExampleIndexRoute
  NotebookAddIndexRoute: typeof NotebookAddIndexRoute
  NotebookIndexRoute: typeof NotebookIndexRoute
  SearchViewIndexRoute: typeof SearchViewIndexRoute
  SystemTrayIndexRoute: typeof SystemTrayIndexRoute
  ConfigsNotebookIndexRoute: typeof ConfigsNotebookIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-tray/': {
      id: '/system-tray/'
      path: '/system-tray'
      fullPath: '/system-tray/'
      preLoaderRoute: typeof SystemTrayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-view/': {
      id: '/search-view/'
      path: '/search-view'
      fullPath: '/search-view/'
      preLoaderRoute: typeof SearchViewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook/': {
      id: '/notebook/'
      path: '/notebook'
      fullPath: '/notebook/'
      preLoaderRoute: typeof NotebookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook-add/': {
      id: '/notebook-add/'
      path: '/notebook-add'
      fullPath: '/notebook-add/'
      preLoaderRoute: typeof NotebookAddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-example/': {
      id: '/form-example/'
      path: '/form-example'
      fullPath: '/form-example/'
      preLoaderRoute: typeof FormExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configs/': {
      id: '/configs/'
      path: '/configs'
      fullPath: '/configs/'
      preLoaderRoute: typeof ConfigsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configs/notebook/': {
      id: '/configs/notebook/'
      path: '/configs/notebook'
      fullPath: '/configs/notebook/'
      preLoaderRoute: typeof ConfigsNotebookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  ConfigsIndexRoute: ConfigsIndexRoute,
  FormExampleIndexRoute: FormExampleIndexRoute,
  NotebookAddIndexRoute: NotebookAddIndexRoute,
  NotebookIndexRoute: NotebookIndexRoute,
  SearchViewIndexRoute: SearchViewIndexRoute,
  SystemTrayIndexRoute: SystemTrayIndexRoute,
  ConfigsNotebookIndexRoute: ConfigsNotebookIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
