import type { SupportLanguage } from '../../const/languages'

export const SALT = '1508404016012'

const langMap: [SupportLanguage, string][] = [
  ['auto', 'auto'],
  ['zh-CN', 'zh-CHS'],
  ['zh-TW', 'zh-CHT'],
  ['en', 'en'],
  ['af', 'af'],
  ['ar', 'ar'],
  ['bg', 'bg'],
  ['bn', 'bn'],
  ['bs', 'bs-Latn'],
  ['ca', 'ca'],
  ['cs', 'cs'],
  ['cy', 'cy'],
  ['da', 'da'],
  ['de', 'de'],
  ['el', 'el'],
  ['es', 'es'],
  ['et', 'et'],
  ['fa', 'fa'],
  ['fi', 'fi'],
  ['fil', 'fil'],
  ['fj', 'fj'],
  ['fr', 'fr'],
  ['he', 'he'],
  ['hi', 'hi'],
  ['hr', 'hr'],
  ['ht', 'ht'],
  ['hu', 'hu'],
  ['id', 'id'],
  ['it', 'it'],
  ['ja', 'ja'],
  ['ko', 'ko'],
  ['lt', 'lt'],
  ['lv', 'lv'],
  ['mg', 'mg'],
  ['ms', 'ms'],
  ['mt', 'mt'],
  ['mww', 'mww'],
  ['nl', 'nl'],
  ['no', 'no'],
  ['otq', 'otq'],
  ['pl', 'pl'],
  ['pt', 'pt'],
  ['ro', 'ro'],
  ['ru', 'ru'],
  ['sk', 'sk'],
  ['sl', 'sl'],
  ['sm', 'sm'],
  ['sr-Cyrl', 'sr-Cyrl'],
  ['sr-Latn', 'sr-Latn'],
  ['sv', 'sv'],
  ['sw', 'sw'],
  ['th', 'th'],
  ['tlh', 'tlh'],
  ['tlh-Qaak', 'tlh-Qaak'],
  ['to', 'to'],
  ['tr', 'tr'],
  ['ty', 'ty'],
  ['uk', 'uk'],
  ['ur', 'ur'],
  ['vi', 'vi'],
  ['yua', 'yua'],
  ['yue', 'yue'],
]

export const sougoLangMap = new Map(langMap)
